---
- name: "Add permission '{{ vcsa_permission.role }}' to user: {{ vcsa_permission.principal }}"
  vmware_object_role_permission:
    hostname: "{{ inventory_hostname }}"
    username: "{{ vcsa_sso_username }}"
    password: "{{ vcsa_sso_password }}"
    validate_certs: no
    role: "{{ vcsa_permission.role }}"
    principal: "{{ vcsa_permission.principal }}"
    object_name: rootFolder
    state: present
  delegate_to: localhost
