- name: Reboot appliance
  vmware_guest:
    hostname: "{{ ova_deployment_hostname }}"
    username: "{{ ova_deployment_username }}"
    password: "{{ ova_deployment_password }}"
    validate_certs: "{{ ova_validate_certs }}"
    name: "{{ inventory_hostname_short | lower }}"
    state: rebootguest
  register: vcsa_reboot
  delegate_to: localhost
  when: |
    (ad_join_command is defined and ad_join_command.changed|bool) or
    (tls_configured is defined and tls_configured.changed|bool) or
    (certificate_configured is defined and certificate_configured.changed|bool)

- name: Wait for VCSA to start
  include_tasks: wait_for_ssh.yml
  when: vcsa_reboot.changed|bool
