---
- name: Set SSH Cyphers
  replace:
    path: /etc/ssh/ssh_config
    regexp: '^Ciphers\s.*aes256-ctr,aes128-ctr$'
    replace: 'Ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
    backup: yes
    validate: "/usr/sbin/sshd -f %s -t"
  register: ssh_ciphers

- name: Set SSH MACs
  replace:
    path: /etc/ssh/ssh_config
    regexp: '^MACs\s.*hmac-sha1$'
    replace: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-sha1'
    backup: yes
    validate: "/usr/sbin/sshd -f %s -t"
  register: ssh_macs

- name: Reload service sshd
  service:
    name: sshd
    state: reloaded
  when: |
    ssh_ciphers.changed|bool or
    ssh_macs.changed|bool
