---
- name: Wait for the SSH Service to become available on the network
  wait_for:
    port: 22
    host: "{{ ansible_host | default(inventory_hostname) }}"
    search_regex: "OpenSSH"
    sleep: 10
    timeout: 1200
  delegate_to: localhost